name: Replace branch name
on:
  pull_request:
    types: [closed]
jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Replace branch name
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            BRANCH_NAME=${{ github.head_ref }}
            find . -name '*' -exec sed -i 's/'"$BRANCH_NAME"'/v48.0.0/g' {} \;
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git commit -am "Replace branch name with v48.0.0"
            git push
          fi
